### ISSUE TITLE
500 Internal server error

### ISSUE THREAD

**Issue by notshi** [drkane/ngo-explorer#130]
Hello,

Apologies if this isn't the place to raise.

Links are currently directed to an error page, for example: https://ngoexplorer.org/country/all?filter-regions=E12000003
![Screenshot-20211110125213-1325x170](https://user-images.githubusercontent.com/1515961/141116398-d1e7b67d-4298-4148-86c0-8bbd98453fc6.png)

Browser: Firefox 94.0.1 (64-bit)

**Comment by drkane** [comment]
It's now working again (I turned it off and on again). Leaving this issue open to keep track of what the actual cause was as I figure it out.

**Comment by notshi** [comment]
Great, thanks @drkane - can confirm it is working again here too.

**Comment by drkane** [comment]
Still not sure what this issue was, but it doesn't seem to have recurred
